# Generated by Django 6.0.1 on 2026-03-17 12:08

import kajli_truck.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KajliTruckEntry',
            fields=[
                ('entry_id', models.CharField(db_index=True, default=kajli_truck.models.generate_entry_id, editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('godownnumber', models.IntegerField()),
                ('cargo_type', models.CharField(choices=[('RBC', 'RBC'), ('LSA', 'LSA'), ('DSA', 'DSA')], max_length=3)),
                ('bags', models.IntegerField()),
                ('truck_number', models.CharField(max_length=50)),
                ('loading_status', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3)),
                ('truckstatus', models.CharField(choices=[('IN - complete', 'IN - complete'), ('IN - pending', 'IN - pending'), ('OUT - complete', 'OUT - complete'), ('OUT - pending', 'OUT - pending')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Kajli Truck Entries',
            },
        ),
    ]
