# Generated by Django 6.0.1 on 2026-03-17 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kajli_truck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kajlitruckentry',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
