# Generated by Django 6.0.1 on 2026-03-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kajli_truck', '0002_kajlitruckentry_entry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='KajliAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godownnumber', models.IntegerField()),
                ('cargo_type', models.CharField(choices=[('RBC', 'RBC'), ('LSA', 'LSA'), ('DSA', 'DSA')], max_length=3)),
                ('adjustment_value', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
