# Generated by Django 6.0.1 on 2026-03-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kajli_truck', '0003_kajliadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='kajlitruckentry',
            name='entry_month',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
