# Generated by Django 6.0.1 on 2026-03-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kajli_truck', '0004_kajlitruckentry_entry_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kajlitruckentry',
            name='cargo_type',
            field=models.CharField(choices=[('RBC', 'RBC'), ('LSA', 'LSA'), ('DSA', 'DSA')], db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='kajlitruckentry',
            name='godownnumber',
            field=models.IntegerField(db_index=True),
        ),
    ]
