# Generated by Django 6.0.1 on 2026-04-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='refresh_token',
        ),
        migrations.AddField(
            model_name='usersession',
            name='session_token',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
