# Generated by Django 6.0.1 on 2026-04-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_usersession_refresh_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='session_token',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
