# Generated by Django 6.0.1 on 2026-03-17 15:14

import django.db.models.deletion
import jswnagaur.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JswSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JswNagaurEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(default=jswnagaur.models.generate_entry_id, editable=False, max_length=16, unique=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('truck_number', models.CharField(max_length=50)),
                ('invoice_number', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('metric', models.DecimalField(decimal_places=3, max_digits=10)),
                ('seal_number', models.CharField(max_length=100)),
                ('entry_date', models.DateField()),
                ('entry_month', models.CharField(blank=True, max_length=20)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jsw_entries', to='jswnagaur.jswsupplier')),
            ],
            options={
                'verbose_name_plural': 'JSW Nagaur Entries',
                'ordering': ['-entry_date', '-serial_number'],
            },
        ),
    ]
