# Generated by Django 6.0.1 on 2026-03-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jswnagaur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jswnagaurentry',
            name='serial_number',
            field=models.IntegerField(db_index=True),
        ),
    ]
