# Generated by Django 6.0.1 on 2026-03-17 09:33

import django.utils.timezone
import night_checking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TruckEntry',
            fields=[
                ('entry_id', models.CharField(db_index=True, default=night_checking.models.generate_entry_id, editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('truck_number', models.CharField(max_length=50)),
                ('transporter_name', models.CharField(max_length=255)),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_date', models.DateTimeField(blank=True, null=True)),
                ('paper_status', models.BooleanField(default=False, verbose_name='Paper Status OK?')),
                ('driver_status', models.BooleanField(default=False, verbose_name='Driver Status OK?')),
                ('tarpulin_status', models.BooleanField(default=False, verbose_name='Tarpulin Status OK?')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], db_index=True, default='IN', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Truck Entries',
                'ordering': ['-entry_date'],
            },
        ),
    ]
