# Generated by Django 6.0.1 on 2026-03-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('night_checking', '0002_transporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckentry',
            name='entry_month',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
