# Generated by Django 6.0.1 on 2026-03-17 07:54

import attendance.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.CharField(db_index=True, default=attendance.models.generate_attendance_id, editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('worklocation', models.CharField(max_length=255)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('attendance_date', models.CharField(db_index=True, max_length=20)),
                ('attendance_month', models.CharField(db_index=True, max_length=20)),
                ('in_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('in_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('out_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('out_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Attendances',
                'ordering': ['-check_in_time'],
            },
        ),
    ]
